name: 'Terraform Apply'
# used GH copilot chat to create this template for me
# action that provisions infrastructure to Azure
on:
  # push:
  #     branches:
  #         - main
  #     paths:
  #         - "**.tf" # Any Terraform file
  #         - "**.tfvars" # Any Terraform variables file
  #         - ".github/workflows/**" # Pipeline changes
  workflow_dispatch:

env:
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    TF_LOG: INFO
    TF_INPUT: false
    name: production
    url: https://portal.azure.com
    WORKING_DIR: "./infra" # Directory containing Terraform files
    TF_VERSION: "1.6.0" # Terraform version to use
    #TF_IN_AUTOMATION: true

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    #use bash shell regardless of github actions runner 
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
# clone repo to runner machine 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
# setup terraform on runner machine
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}

    - name: Terraform Output
      run: terraform output